name: Download Model Weights

on:
  push:

jobs:
  download-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 pyannote.audio==2.1.1 soundfile

      - name: Download model weights
        run: |
          python -c "
          from pyannote.audio.tasks.embedding import SpeakerEmbedding
          model_name = 'pyannote/speaker_embedding'
          model = SpeakerEmbedding.from_pretrained(model_name)
          torch.save(model.state_dict(), './models/speaker_embedding_model.pth')
          "

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update model weights" || echo "No changes to commit"
          git push
