name: Download Model Weights

on:
  schedule:
    # Schedule the workflow to run every day at a specific time (e.g., 00:00 UTC)
    - cron: '0 0 * * 0'
  pull_request:
    types:
      - opened
  push:

jobs:
  download-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 pyannote.audio==2.1.1

      - name: Download model weights
        run: |
          python -c "
          from pyannote.audio import Pipeline
          HUGGINGFACE_DIARIZATION_MODEL = 'pyannote/speaker-diarization'
          HUGGINGFACE_TOKEN = '${{ secrets.HUGGINGFACE_TOKEN }}'
          pipeline = Pipeline.from_pretrained(HUGGINGFACE_DIARIZATION_MODEL, use_auth_token=HUGGINGFACE_TOKEN)
          pipeline.save_pretrained('./models/diarization_model')
          "

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update model weights" || echo "No changes to commit"
          git push